# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: afdc8c5d4dd521516f0d9c26ffc25bcf275ad3c81db33957147e71935a9c21b56a03ab6d8ea78dc7e6c654fe3312455a7a5c311e3299728d104d80545d88da9d

test:
  secret_key_base: 26620c57aa277fba3c859dfa4e177dd408cd81eae9551daaaa3a80927ea752878ba9d61be3e338c2a12ab0b73c785d5a8bace13f15d372ea417b3085bd94f8cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
